### ISSUE TITLE
Investigate labeling SLBE sooner

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/park-tiles#119]
A quote from an email sent to Web Services Division by SLBE’s Chief of Interpretation:

> I noticed that when opened the only MI NPS site that can be seen on the map is "Pictured Rocks". There is text for all seven MI sites below the map but at first glance a visitor to the page would only think there was one nps site in Michigan and maybe Isle Royale NP which is featured as the banner image.

**Comment by makella** [comment]
SLBE should be labeled (I know because the park is displayed as a polygon at the opening scale).  I think what is happening is that we are at a tile boundary and the state label for Michigan and the large great lake label is blocking the placement of the label for SLBE.  

I'll take a look to see if I can modify the location of the state label using CartoCSS to see if we can get that labeling sooner.  I'll also double check with Jim on the data side to make sure that the minzoompoly for both the label and park match.

With regards to the tile boundary at the opening scale (z6) for MI, you can see below that there is limited space available to place a long label like 'Sleeping Bear Dunes':

![image](https://cloud.githubusercontent.com/assets/1566273/6169784/17b13356-b28d-11e4-9acd-9f1f339f3515.png)

I think we are seeing the same issue at z7:

![image](https://cloud.githubusercontent.com/assets/1566273/6169849/6b52a5bc-b28d-11e4-9a9f-815dcce19b40.png)

Finally, at z8 there is enough 'room' for the label to get placed.  We've noticed this in other areas too typically park labels getting blocked by city labels.  We put the park labels higher in the placement hierarchy... that might be something we can do with state labels (put them lower in the placement hierarchy) but then we would be sacrificing state labels in some places at these opening scales which might not be the best idea.

I'll see what I can do.

**Comment by nateirwin** [comment]
The Chief of Interp sent me another email on 5/26/2015 inquiring about the status of this issue. Just wondering if it is something we may be able to take care of with a quick fix?

**Comment by jimmyrocks** [comment]
As far as the database is concerned, it should get it's label at zoom 6: https://github.com/nationalparkservice/mapbox-studio-projects/blob/56743182829164488e7da5330db4a63ec11116f8/park_tiles/park_tiles_data_process/nps_data_compilation/scripts/cleanup/label_point_calc_tasks.sql#L279-280

Unfortunately, this means it won't be easy to change and won't be a quick fix.

**Comment by jakecoolidge** [comment]
Since there's only SLBE in that part of Michigan, I propose we use CartoCSS to move the Michigan label down along the y axis.
zoom 5
![z5](https://cloud.githubusercontent.com/assets/11392872/7964914/7e009a88-09d7-11e5-9c25-98864f41b3c1.png)
zoom 6
![z6](https://cloud.githubusercontent.com/assets/11392872/7964913/7e006e6e-09d7-11e5-810a-355884a29609.png)
zoom 7
![z7](https://cloud.githubusercontent.com/assets/11392872/7964915/7e06c70a-09d7-11e5-8a97-c0b1c152e1dd.png)
zoom 8
![z8](https://cloud.githubusercontent.com/assets/11392872/7964916/7e0f285a-09d7-11e5-9d2d-621e1c47cce6.png)

**Comment by makella** [comment]
@jakecoolidge thanks for taking a look at this.  I've implemented what you suggested and re-published the map.  I would like to see if there is another way to implement this change without additional CartoCSS.  I've done this in Park Tiles, Park Tiles Imagery, and Park Tiles Slate.  I will spend some time later today adding to the exploded version.

thanks again.

**Comment by makella** [comment]
All maps should be updated now.

**Comment by nateirwin** [comment]
Thanks, looks great!
