### ISSUE TITLE
Determine if there are alternative ways to do the land-clip mask

### ISSUE THREAD

**Issue by jimmyrocks** [nationalparkservice/park-tiles#122]
Maybe we can move to Mapbox Terrain v2 and use CartoCSS to do something similar to the mask.

**Comment by makella** [comment]
consolidating issues related to this

**Comment by makella** [comment]
@jimmyrocks you will be happy I think I might have cracked this nut... finally!  More to come.

**Comment by jimmyrocks** [comment]
Exciting! I want to know more!

**Comment by nateirwin** [comment]
Me too!

**Comment by makella** [comment]
I think I figured it out!! @jakecoolidge do you have a prototype id for terrain V2?  I've done this with v1 but want to see if it'll work the same with v2.

**Comment by jakecoolidge** [comment]
I have a style on my local drive that is just hillshade v2... I integrated this style into an [older test version of Places Viewer](http://www.nps.gov/maps/full.html?mapId=b1ec9b4d-7e9d-4539-9c26-99fe763bf38b). This style uses hillshade v2 as an underlay (nps.9b6d0fa5) and places two additional style (nps.6b727d4b, nps.ef4be385) over it--but this of course is one step shy of engaging with the land clip issue directly. Last week I had been tinkering with it before I set it aside to attend to other matters. If you'd like to plug the style sheet from hillshade v2 directly into your style, let me know how best I can share these with you. I haven't put this stuff on the repo since it's all been experimental up to this point.

**Comment by makella** [comment]
Ok, cool.  I'll just use your mapbox id in my test map.  If this works out, I'll let you know. Thanks!

**Comment by jakecoolidge** [comment]
Awesome!

**Comment by makella** [comment]
@jakecoolidge here is a Builder map with your terrain layer... take a look and let me know what you think. I adjusted some land colors on the Park Tiles redesign so we can go over those after you've had a chance to look at this.  I think it is looking good!  And now @jimmyrocks will jump for joy because we don't need a mask.

http://www.nps.gov/maps/embed.html?mapId=5bb01010-51aa-4065-b877-0babdf7c91d4

p.s.-  Park Tiles 3 is still under development so what you see in the map is not final but a work in progress.

**Comment by makella** [comment]
We are very close to solving this!

**Comment by jakecoolidge** [comment]
Your map sample looks great. Glad you've made some progress you're happy with!

**Comment by makella** [comment]
Thanks! Getting there.  Let me know what you think of the map with your hillshade v2... for comparison, here is the same map as above with hillshade v1 masked the same way:

 http://www.nps.gov/maps/embed.html?mapId=e3e50749-e58e-4919-afc3-3541a768d325

**Comment by makella** [comment]
Hallelujah! This is done and figured out.
