### ISSUE TITLE
Revive "compare" tool for Park Tiles viewer

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/park-tiles#155]
I can add this to the "npmap-website" repository, but I thought I'd start the discussion here: What do you all think about reviving the Park Tiles compare tool that makes it easy to see Park Tiles next to commercial map tiles (Bing, Mapbox, etc.)? A lot of people seemed to "get" why we are building Park Tiles after they saw how much better our basemap is inside National Park Service boundaries.

Just something I've been thinking about...

**Comment by makella** [comment]
I think this is a good idea.  Instead of comparing to Park Tiles, I would compare to the version of Park Tiles built with Places data (similar to when we first did this having Tom put his data in OSM and then showing how much detail we were adding).

I say this because if we compare to Mapbox, then the maps will pretty much look the same since we are pulling from the same datasource they are.

But yes, let's do it... that was such a cool tool!

**Comment by nateirwin** [comment]
Great. Can you sketch out a wireframe and jot down a few notes about what you'd like to see? I'd like to implement this soon.

**Comment by makella** [comment]
for sure.

**Comment by makella** [comment]
@jakecoolidge do you want to take a stab at wireframing this out? The compare tool will use the version of Park Tiles that you are building with Places data. You can see some screenshots of the one we (quickly) made a few years ago for State of the Map where we compared commercial basemap providers with a map of GRSM using OSM data that Tom had uploaded.  The full screenshot of the app is on pg. 21. 

http://www.nps.gov/npmap/slides/improving-osm-data-in-our-national-parks.pdf

Let us know if you have any questions.

**Comment by jakecoolidge** [comment]
I've come up with a two basic ideas for what this could look like. Features common to both variations include:
- A "Find a location" input bar
- Home and Zoom controls
- Uses only Park Tiles Standard. My rationale is to keep the interface relatively simple, and eliminating the drop-down menu for Imagery and Slate frees up a few pixels for the map. It will be particularly hard to see all the added features in Places with Imagery since we don't symbolize roads and trails in that basemap.
- Designed to fit in our standard page layout. This wireframe uses a map element which is 546px tall, but a reduction to 500px is definitely possible.
- The position of the map view within the Places landing page is only for demonstration. I don't yet have a perspective on where this comparison view should reside.

One variation employs a side-by-side approach, like the one used a few years ago that Mamata referenced. The two data sources are noted along the top bar.
![park-tiles-comparison-wireframe-sidebyside](https://cloud.githubusercontent.com/assets/11392872/7757899/fea77ca2-ffc2-11e4-9d74-74b7afc82f75.png)


The other variation employs a swipe feature like the one I found [here,](https://www.mapbox.com/blog/mapbox-terrain-data-update/) on Mapbox's blog. The central axis can be moved from left to right to reveal the map using OSM on the left, and NPS data on the right. The two sources are labeled near the axis, again following the Mapbox example.
![park-tiles-comparison-wireframe-swiping](https://cloud.githubusercontent.com/assets/11392872/7757926/2823fc22-ffc3-11e4-9b61-119add595a30.png)

**Comment by jakecoolidge** [comment]
I've created a demo map of Park Tiles drawing roads, trails, buildings, and points of interest from Places; have a look [here.](http://www.nps.gov/maps/full.html?mapId=f97cbf73-91ea-4c05-ae22-32864393131e) It will give you a live look at the Big Meadows campground in Shenandoah (among other places) featured in my wireframes above.

**Comment by makella** [comment]
nice! can you give the parking lots a different fill than white? we don't currently symbolize parking lots on park tiles but something that doesn't conflict with the building gray would probably work.

**Comment by jakecoolidge** [comment]
I'll look into it straight away.

**Comment by makella** [comment]
related to: https://github.com/nationalparkservice/park-tiles/issues/105

**Comment by nateirwin** [comment]
Great to see our data out there!

**Comment by makella** [comment]
I think both viewer ideas are good.  I guess which option we go with will be easier to decide once we figure out more about the Places landing page on Monday. 

@jakecoolidge what basemaps do you think we should compare against?  In the past we used Bing, Google (which we no longer have a license to), and Mapbox.  I'd be interested to see if you've noticed parks in the version of Park Tiles built using Places data that surpass what we currently have (I'm sure there are many! Especially smaller parks that don't really have any data in OSM).  That would be good to know too so we can set some pre-zoomable places in the compare tool.

**Comment by jakecoolidge** [comment]
This is something I want to spend a little more time researching. I chose a portion of Shenandoah for my wireframe specifically because I think Places data in that area is already showing some improvement over OSM. (I also seeded its roads, trails, and parking lots, so I'm fairly familiar with what's in there.) If you know of particular parks that are poorly represented in OSM that you could point me to, that would be great. With some digging around, I could probably come up with some more examples. Of course, if I got back to seeding that road data, that would help a lot...Death Valley came online a couple days ago, I should check how it's rendering in Mapbox now.

What's a good timeline for getting a roster of demonstration parks together? And how many pre-zoomable places would you guys like to support?

**Comment by makella** [comment]
I'd say to look at parks on Park Tiles that are rural.  Those ones tend to not have good coverage in OSM. Even a park like GRSM did not until Tom added his data.  Even if a park does have what seems to be good coverage, roads and trails are often times incorrect.  Another idea is to look through which parks/regions have contributed their data to Places -- that's probably a good way to start.  There's a list, right?

In terms of timeline, I'd say to have an idea of four or five parks upfront which shouldn't take too long. It will also be a good exercise to evaluate Park Tiles built with Places data across multiple parks.

**Comment by jakecoolidge** [comment]
Sounds good. I should have a short list together by Tuesday. And yes, we do have a data seed tracking sheet that will give me the recent contributions--I'll consult this.

**Comment by nateirwin** [comment]
@jakecoolidge: This is still one I think we should spend some more time on. It would be great to come up with a list of "bookmarks" that we use to spot check changes and new versions of Park Tiles.

Cc/ @mtaylorlong

**Comment by jakecoolidge** [comment]
I'll take a look at this and have an initial list by the end of the week (really).

**Comment by jakecoolidge** [comment]
I've started a list of bookmarks on our scratch wiki, have a look [here.](https://github.com/nationalparkservice/npmap-scratch/wiki/Bookmarks-for-Places-and-Park-Tiles)

Let me know if this is a good place to house this information, and also if there are areas I should add. I hope to grow this list over time, and I encourage everyone else to do so as well.

**Comment by nateirwin** [comment]
Was going through some old notes and saw a note about supporting v1 of Park Tiles in the compare tool. Don't know if this is possible, but thought I'd plop it down here so I don't lose the thought.

**Comment by cwlawlis802** [comment]
Are we good to close here @nateirwin @jakecoolidge? Looks like we have PT2 and 2.1 along with external map sources comparable to PT3 here: https://www.nps.gov/npmap/tools/park-tiles/compare/?v=3#4/39.06/-95.98.

The only thing still missing is the POI overlay in the PT3 side of the viewer.

**Comment by nateirwin** [comment]
I think we're good, other than the POI overlay. Definitely need to add that.

**Comment by cwlawlis802** [comment]
The POI overlay is being tracked here https://github.com/nationalparkservice/npmap-website/issues/120 so I'm going to close this out.
